//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sign", ReplyAction="http://tempuri.org/IService/SignResponse")]
    System.IO.Stream Sign(System.IO.Stream fs);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Sign", ReplyAction="http://tempuri.org/IService/SignResponse")]
    System.Threading.Tasks.Task<System.IO.Stream> SignAsync(System.IO.Stream fs);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPublicKey", ReplyAction="http://tempuri.org/IService/GetPublicKeyResponse")]
    string GetPublicKey();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPublicKey", ReplyAction="http://tempuri.org/IService/GetPublicKeyResponse")]
    System.Threading.Tasks.Task<string> GetPublicKeyAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.IO.Stream Sign(System.IO.Stream fs)
    {
        return base.Channel.Sign(fs);
    }
    
    public System.Threading.Tasks.Task<System.IO.Stream> SignAsync(System.IO.Stream fs)
    {
        return base.Channel.SignAsync(fs);
    }
    
    public string GetPublicKey()
    {
        return base.Channel.GetPublicKey();
    }
    
    public System.Threading.Tasks.Task<string> GetPublicKeyAsync()
    {
        return base.Channel.GetPublicKeyAsync();
    }
}
